site_name: r-type
site_url: https://antoine-df.github.io/rtype_docs/
nav:
    - Home: index.md
    - Dev documentation : devDoc.md
    - Protocol documentation : protocolDoc.md
    - About: about.md
theme: readthedocs